from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name="index"),
    path('home/',views.home,name="home"),
    path('adminsite/',views.admin,name="admin"),
    path('login/',views.loginPage,name="login"),
    path('register/',views.registerPage,name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('search/',views.search,name="search"),
    path('my_work/',views.myWork,name="my_work"),
    path('my_work/<slug:slug>/',views.myWorkDetail,name="my_work_detail"),
    # path('my_work/<slug:slug>/create',views.createChapter,name="create_chapter"),
    # path('my_work/<slug:slug>/<int:chapter_number>/edit',views.editChapter,name="edit_chapter"),
    path('read/<slug:slug>/<int:chapter_number>/',views.read,name="read"),
    path('detail/<slug:slug>/',views.detail,name="detail"),
    path('profile/general',views.profile_general,name="profile_general"),
    path('profile/follow',views.profile_follow,name="profile_follow"),
    path('profile/change_pass',views.profile_change_pass,name="profile_change_pass"),
    path('rate/',views.rate,name="rate"),
    path('n_rate/',views.nRate,name="n_rate"),
    path('follow/',views.follow,name="follow"),
    path('manage/',views.manage,name="user_manage"),
    path('ban/',views.ban,name="ban"),
    path('lock_out/',views.lock_out,name="lock_out"),
    path('about_us/',views.about_us,name="about_us"),
    path('list/',views.novelList,name="novel_list"),
    path('list/<str:first_letter>/',views.novelList,name="novel_list"),
    # path('list/<slug:slug>/',views.novelList,name="novel_list"),
    path('increase_views/',views.increase_views,name="increase_views"),
    path('base/',views.base,name="base"),
    path('post_comment/',views.postComment,name="post_comment"),
    path('advanced_search/',views.advancedSearch,name="advanced_search"),
    path('action/',views.action,name="action"),
    path('action/tags_list',views.tagsList,name="tags_list"),
    path('action/create_novel/',views.createNovel,name="create_novel"),
    path('action/<slug:slug>/create',views.createChapter,name="create_chapter"),
    path('action/<slug:slug>/edit',views.editNovel,name="edit_novel"),
    path('action/<slug:slug>/<int:chapter_number>/edit',views.editChapter,name="edit_chapter"),
    path('action/manage_list/',views.manageList,name="manage_list"),
    path('action/delete',views.deleteNovel,name="delete_novel"),
    path('action/<slug:slug>/manage',views.manageNovel,name="manage"),
    path('action/nav/<slug:slug>',views.navbarNovel,name="navbar_novel"),
    path('action/profile',views.profile_details,name="profile_details"),
]