# Generated by Django 3.2.5 on 2022-01-23 15:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0041_comment_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(default='Hello world'),
        ),
    ]
