# Generated by Django 3.2.5 on 2022-01-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0043_remove_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
