# Generated by Django 3.2.5 on 2022-01-25 13:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0044_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
