# Generated by Django 3.2.5 on 2022-01-26 14:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0046_alter_novel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor.fields.RichTextField(default='description'),
        ),
    ]
