# Generated by Django 4.0 on 2022-02-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0050_remove_userinfo_phone_userinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
