# Generated by Django 4.0 on 2022-02-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0051_alter_chapter_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
