# Generated by Django 4.0 on 2022-02-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0052_alter_chapter_update_date_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='images/noava.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.BooleanField(choices=[(True, 'Finished'), (False, 'Ongoing')], default=False),
        ),
    ]
