# Generated by Django 4.0 on 2022-02-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0056_alter_userinfo_hobby_alter_userinfo_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
