# Generated by Django 4.0 on 2022-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook', '0057_alter_userinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
